changes

diff --git a/.github/workflows/update-readme.yml b/.github/workflows/update-readme.yml
--- a/.github/workflows/update-readme.yml
+++ b/.github/workflows/update-readme.yml
@@ -32,12 +32,28 @@ jobs:
           # Realiza la solicitud a la API y guarda la respuesta en latest-posts.json
           curl -H "X-CODEGEEKERY: $HMAC_KEY" "https://lg-resume-calculations-note.trycloudflare.com/api/latest-post" -o latest-posts.json
 
-      - name: Update README
+      - name: Update README with Latest Posts
         run: |
-          echo "# Latest Blog Posts" > README.md
-          echo "" >> README.md
-          jq -r '.[] | "- ![\(.title)](\(.mainImage.asset.url)) 
-          [\(.title)](https://codegekery.com/posts/\(.slug.current))"' latest-posts.json >> README.md
+          if [ ! -f latest-posts.json ]; then
+            echo "Error: latest-posts.json not found!" >&2
+            exit 1
+          fi
+
+          # Extraer los 3 últimos posts
+          latest_posts=$(jq -r '.[0:3] | map("- <img src=\"\(.mainImage.asset.url)\" width=\"100\" height=\"100\" alt=\"\(.title)\"/>  \n  [\(.title)](https://codegekery.com/\(.slug.current))\n") | join("\n")' latest-posts.json)
+
+          # Copia el contenido actual del README
+          cp README.md README.tmp
+
+          # Insertar los posts después de cada sección
+          awk -v posts="$latest_posts" '
+            /### Tecnologias/ {print; print posts; next} 
+            /### Redes Sociales/ {print; print posts; next} 
+            {print}
+          ' README.tmp > README.md
+
+          rm README.tmp
+
 
       - name: Commit and push if changed
         run: |
